---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/psf/black.git
    rev: 22.6.0
    hooks:
        - id: black
          language_version: python3

  - repo: https://github.com/PyCQA/isort.git
    rev: 5.12.0
    hooks:
        - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: v0.971
    hooks:
        - id: mypy

  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.3.0
    hooks:
        - id: remove-crlf
        - id: remove-tabs

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
