comment: "backup server configuration for normal operation"
logger:
  filename: 'logfile.log'

debug:
  remote_logging_logfile_path: '/mnt/hdd/share/Maintenance/base.log'
  remote_ssh_connect_string: 'root@192.168.0.11'

backup:
  nas_name_in_ssh_config: nas
  rsync_source: backup_data_source

process:
  seconds_between_backup_end_and_shutdown: 300
  time_between_backups:
    days: 1
    hours: 0
    minutes: 0
